//QUE ES UN API .
//APLICATION PROGRAMMIG INTERFACE
// ES UN SERVICIO EL CUAL PUEDE PROVEER INFORMACIO O TAMBIEN PUEDE CREARLA

//EN JS EXISTE UNA FUNCION LA UAL SE ACERGA DE PODER HACER LA PETICION
//FETCH ()
// EXISTE TIPO DE PETICIONES DEONDE LAS PRINCIPALES SON 
//GET = OBTNER INFORMAION
//POST = CREAR DATOS
//PUT = ACTUALIZAR DATOS 
//DELETE = ELIMINAR DATOS 
//FUNCTION ASYNC 